// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNDkglCoSS4wINHo2Wjwg1oJj_mK8cNIA',
    appId: '1:768386623591:web:375c4c39c58a910ae08cc2',
    messagingSenderId: '768386623591',
    projectId: 'app-pastel-c2439',
    authDomain: 'app-pastel-c2439.firebaseapp.com',
    storageBucket: 'app-pastel-c2439.appspot.com',
    measurementId: 'G-X14WRVMQ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP36eP_VNLqcGDcPbJ41AET9jfOPbp_U0',
    appId: '1:768386623591:android:c2639d21a11f7e11e08cc2',
    messagingSenderId: '768386623591',
    projectId: 'app-pastel-c2439',
    storageBucket: 'app-pastel-c2439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg0jcJ7mEy0RmieFIaZXUthWrjEH_6__Q',
    appId: '1:768386623591:ios:8aa7b0fbd06780cee08cc2',
    messagingSenderId: '768386623591',
    projectId: 'app-pastel-c2439',
    storageBucket: 'app-pastel-c2439.appspot.com',
    iosBundleId: 'com.joao.trilhaflutter.trilhaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg0jcJ7mEy0RmieFIaZXUthWrjEH_6__Q',
    appId: '1:768386623591:ios:fb7ffefc27277adee08cc2',
    messagingSenderId: '768386623591',
    projectId: 'app-pastel-c2439',
    storageBucket: 'app-pastel-c2439.appspot.com',
    iosBundleId: 'com.joao.trilhaflutter.trilhaapp.RunnerTests',
  );
}
